FROM python:3.9-slim
WORKDIR /app

COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn==20.1.0

COPY backend/ .

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--workers", "2", "server:app"]